# @package _global_

model:
  _target_: main.module_conditional.Model
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3

  pretrained_model_name_or_path: cvssp/audioldm2-large